### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by jamiemiller1486** [LANResources/dealer-locator#3]
http://dealers.backofficeapps.com/support

Need to remove the following under Business Development

Action Plan Assistance
Biozyme Connect

Redeem Action Points needs to show Jennifer Miller and Not Casie Greenwood

**Comment by reed** [comment]
Can you please add this to the dealer center repository so I can reference it in a commit?

**Comment by jamiemiller1486** [comment]
Damn i put it in the wrong one.  Sorry.

**Comment by reed** [comment]
No worries.
